services:
  - type: web
    name: agentkitJS-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: CDP_API_KEY_NAME
        value: your_cdp_api_key_name
      - key: CDP_API_KEY_PRIVATE_KEY
        value: your_cdp_api_key_private_key
      - key: OPENAI_API_KEY
        value: your_openai_api_key

  - type: web
    name: agentkitJS-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    depends_on:
      - agentkitJS-backend